#
# Copyright (c) 2023 Christian Mazakas
# Copyright (c) 2023 Alan de Freitas
# Copyright (c) 2021-2023 Sam Darwin
# Copyright (c) 2020-2021 Peter Dimov
# Copyright (c) 2021 Andrey Semashev
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Official repository: https://github.com/CPPAlliance/http_proto/
#

name: CI

on:
  pull_request:
  push:


concurrency:
  group: ${{format('{0}:{1}', github.repository, github.ref)}}
  cancel-in-progress: true

env:
  GIT_FETCH_JOBS: 8
  NET_RETRY_COUNT: 5
  DEFAULT_BUILD_VARIANT: debug,release
  UBSAN_OPTIONS: "print_stacktrace=1"
  ASAN_OPTIONS: "detect_invalid_pointer_pairs=2"

jobs:
  antora-win:
    name: Antora Docs Win
    runs-on: windows-2022
    steps:
      - name: Clone Http.Proto
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup C++
        uses: alandefreitas/cpp-actions/setup-cpp@v1.8.2
        id: setup-cpp
        with:
          compiler: clang
          version: 17

      - name: Build Antora Docs
        run: |
          cd doc
          .\build_antora.bat

      - name: Create Antora Docs Artifact
        uses: actions/upload-artifact@v3
        with:
          name: antora-docs
          path: doc/build/site
